name: personasynth
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.10
  
  # Core web framework
  - flask=2.3.3
  - flask-cors=4.0.0
  
  # Data science and ML
  - numpy=1.24.3
  - scikit-learn=1.3.0
  - pandas=2.0.3
  
  # Natural Language Processing
  - spacy=3.7.2
  
  # Web scraping and HTTP requests
  - requests=2.31.0
  - beautifulsoup4=4.12.2
  - lxml=4.9.3
  
  # PDF processing
  - pypdf2=3.0.1
  
  # Graph processing
  - networkx=3.1
  
  # Database and data formats
  - sqlite
  
  # Development tools
  - pip=23.2.1
  
  # Pip-only dependencies (not available via conda)
  - pip:
    # LangChain and Google AI
    - langchain==0.1.0
    - langchain-google-genai==0.0.6
    - langchain-community==0.0.13
    - google-generativeai==0.3.2
    
    # Additional NLP and ML tools
    - transformers==4.35.0
    - torch==2.1.0
    - sentence-transformers==2.2.2
    
    # Vector databases and embeddings
    - chromadb==0.4.18
    - faiss-cpu==1.7.4
    
    # Text processing utilities
    - textblob==0.17.1
    - nltk==3.8.1
    
    # Additional PDF processing
    - pdfplumber==0.9.0
    - pymupdf==1.23.8
    
    # Web scraping enhancements
    - selenium==4.15.0
    - newspaper3k==0.2.8
    
    # Data validation and parsing
    - pydantic==2.5.0
    
    # Async support
    - aiohttp==3.9.0
    - asyncio-throttle==1.0.2
    
    # Development and testing
    - pytest==7.4.0
    - pytest-asyncio==0.21.1
    - black==23.9.1
    - flake8==6.1.0
    
    # Logging and monitoring
    - structlog==23.2.0
    
    # Configuration management
    - python-dotenv==1.0.0
    
    # Additional utilities
    - tqdm==4.66.1
    - python-dateutil==2.8.2